### ISSUE TITLE
send.c: lvalue errors

### ISSUE THREAD

**Issue by octeron** [epiphani/bahamut#12]
PGC-S-0058-Illegal lvalue (send.c: 492)
PGC-S-0094-Illegal type conversion required (send.c: 492)
PGC-S-0058-Illegal lvalue (send.c: 1289)
PGC-S-0094-Illegal type conversion required (send.c: 1289)
PGC-S-0058-Illegal lvalue (send.c: 1298)
PGC-S-0094-Illegal type conversion required (send.c: 1298)
PGC-S-0058-Illegal lvalue (send.c: 1421)
PGC-S-0094-Illegal type conversion required (send.c: 1421)
PGC-S-0058-Illegal lvalue (send.c: 1525)
PGC-S-0094-Illegal type conversion required (send.c: 1525)
PGC-S-0058-Illegal lvalue (send.c: 1552)
PGC-S-0094-Illegal type conversion required (send.c: 1552)
PGC-S-0058-Illegal lvalue (send.c: 1579)
PGC-S-0094-Illegal type conversion required (send.c: 1579)
PGC-S-0058-Illegal lvalue (send.c: 1691)
PGC-S-0094-Illegal type conversion required (send.c: 1691)
PGC-S-0058-Illegal lvalue (send.c: 1832)
PGC-S-0094-Illegal type conversion required (send.c: 1832)
PGC-S-0058-Illegal lvalue (send.c: 1957)
PGC-S-0094-Illegal type conversion required (send.c: 1957)
PGC-S-0058-Illegal lvalue (send.c: 2022)
PGC-S-0094-Illegal type conversion required (send.c: 2022)
PGC-S-0058-Illegal lvalue (send.c: 2048)
PGC-S-0094-Illegal type conversion required (send.c: 2048)

**Comment by epiphani** [comment]
Insufficient information.
